---
title: "Positive or negative influence"
author: "Luigi Negro, Federico Piazza, Beatrice Stocco"
date: '2022-03-22'
output: 
  html_document: 
    citation_package: biblatex
    toc: yes
    bibliography: projectQuant.bib
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Introduction 1


# Twitter 2

One of the most useful social media platform to conduct data mining on is Twitter. It comes to no surprise the fact that its top users, i.e. the most followed ones, are celebrities and mass media companies. [Kwak,  Lee,  Park,  &  Moon,  2010] Such a result is further supported by a finding by Kwak et al.(2010), according to whom the level of reciprocity on Twitter following is as low as 22.1%. This is the reason why most of the research activities are carried out using data coming from Twitter.

The first data mining activities were conducted around 2013 with the scope of highlighting how Twitter played a central role in spreading awareness after a natural disaster occured.[cit]. Further steps involved using Twitter's data to predict the happening of those same phenomena [A sentiment Aware contextual model for real time disaster prediction using twitter data. [2021]; weakly supervised and Online learning of word models for classification to detect disaster reporting tweets[2018]}. Similar analyses have been performed to forecast political election's results [Can we vote with our tweet? On the perennial difficulty of election forecasting with social media[2015]] and are now being applied to the cryptocurrency and stock markets.

In particular, at the base of these predictions is a well tested hypothesis according to which investors are not rational, despite what classical theories have been arguing[Fama 1970]. Behavioural researchers have indeed shown that the market is driven by investor's psychology. [De Longhi et al, 1990] referred to the strategies followed by noise traiders as positive-feedback strategies, that are reflected in the tendency of buying stocks when prices are increasing and selling them when they are decreasing, following a so-called herd behaviour. Such a trend cannot be reverted, despite the presence of rational investors who could potentially trade against noise traders. A similar strategy has proven to be ineffective for different reasons. The two most relevant according to Shiller [2003] are represented by short-selling constraints and risk aversion of the investors themselves. 
On the bright side, rational arbitrageurs can still exploit this condition of theirs to their advantage: they can indeed anticipate the trend, contributing to an even higher effect in price change.  
In this sense, investigating the noise traders' moods is crucial in predicting the market development. Schwarz 1990 studied the correlation between mood and risk and found out that people in positive moods perceive the risk as an opportunity, whereas people in negative moods are more likely to see the danger. [Bollen et al, Twitter mood predicts the stock market] was able to correlate the change in some public's mood dimensions like calmness to a shift in DJIA values within a time lag of 3-4 days, thus suggesting a possible tracking of these factors and prediction of future stock prices. The question, though remains on the accuracy of such predictions and the reversion of these effects.
[Using Twitter] found evidence that follower-weighted social mood levels can predict share returns, even though this was not true if simple aggregation of mood states was performed. Indeed, they hypothesized the reason behind such a behavior could be explained in light of emotional contagion, according to which individuals influence each other based on their active network. in 2019 [Informational role of social media] another research was conducted in this field and it was demonstrated that relevant information could be found on Twitter, in particular regarding analyst recommendation changes, target price changes, quarterly earnings surprises and IPO opening prices. Besides this conclusion, that was in line with other papers, they also studied another factor with relevant implications in terms of stock return quality of predictions. Specifically, they found that Twitter sentiment analysis constituted a stronger predictor for smaller firms, i.e. firms less covered by analysts.
Last but not least, [Alexander V. Porshnev, Valeria V. Lakshina Ilya E. Red'kin] studied the contribution of emotional makers to the ARMAX-GARCH model and demonstrated they provided both a smaller BIC and improved likelihood function.

Inspired by the literature on stock return predictability, researchers are now studying the predictability of a new asset class: cryptocurrency. One of the fundamental differences with respect to stocks is that, just like any other currency, cryptocurrency has no fundamental value. On the other hand, it has a similar pattern when it comes to investor's decision taking process, characterized by the so called "herding behavior" [Herding behavior and contagion in the cryptocurrency market; Herding behavior in cryptocurrency markets; Testing for herding in the cryptocurrency market] 

Based on this hypothesis [Muhammad Abubakr Naeem; Imen Mbarki3; Muhammed Tahir Suleman; Xuan Vinh Vo5; Syed Jawad Hussain Shahzad] have conducted a research to investigate the predictability of cryptocurrencies, using the Twitter happiness sentiment. The study revealed a significant non linear Granger casuality across the sample and it indicated that the Hapiness Sentiment was a significant predictor, except for Dash. They also recognized the relevance of some factors in delivering an accurate and reliable prediction: market condition (bearish, normal, or bullish) and the strength of the sentiment (high/low). In 2018 Naseking and Chen used machine learning techniques to construct sentiment indices and adding those values they were able to improve the predictability of logreturns both in and out the sample. They also used an IGARCH approach and were able to build an accurate model for the volatility prediction, adding a squared sentiment predictor. Other works and researches included Mai et al. (2018) and Cheuque Cerda and Reutter (2019).

With our work we intend to bring more evidence to the predictability of cryptocurrency prices, in particular Bitcoins. 

#Sentiment analysis

“If you are not paying for it, you're not the customer; you're the product being sold.” This is a famous quote by Andrew Lewis and is especially true for apps based on user generated content. The data here produced are made available in the form of unstructured data, i.e. data not stored in a structured database. They encompass text, emails, images and so much more. As the majority of the data come in this form new techniques have emerged that allow for them to be analysed and exploited. These techniques are part of the so called "text mining", a research branch that focuses on "extracting the data, transforming it into information and making it useful for various types of decision making". [Text mining for Big Data] The process is characterized by different steps: first in line is data clearing and organizing to best suit the goals of the research. After that, relevant words are extracted, the so called N-grams, and relationship between them are analysed with the objective of dividing words into categories. Such a partitioning allows for research questions to be addressed and conclusions to be drawn. 

Some of the text mining techniques include classification and clustering, sentiment analysis and natural language processing. The latter represents a broader technique that performs different types of analysis, namely summarization, part of speech tagging, text categorization and sentiment analysis.

Particularly relevant to our research is the latter, as emotions have been proved to be key drivers in the process of investing. "Sentiment analysis is a series of methods, techniques, and tools about detecting and extracting subjective information, such as opinion and attitudes, from language."[The Evolution of Sentiment Analysis] It has historically focused on  polarity, meaning the positivity or negativity expressed in a text, but is now moving to a more accurate detection of different emotions (frustration, joy, anger, sadness, excitement).

The first paper using sentiment analysis dates back to 1940, where opinions on various public issues were investigated. A similar analysis was performed a couple years later on countries that mostly suffered during WW2.
But it is not until the early 21st century that more and more papers were published. In 2010 Sitaram Asur and Bernardo A. Huberman used data from Twitter to build a linear regression model to predict box-office revenues of movies in advance of their release. The predictor used was rate of chatter, but they highlighted how a sentiment analysis improved predictions after a movie was released. In particular, they constructed a sentiment analysis classifier to distinguish positive, negative or neutral texts. They then created two factors: Subjectivity and Polarity. With the first they were able to confirm their hypothesis, according to which "there were more sentiments discovered in tweets for the weeks after release, than in the pre-release week". The polarity factor, i.e. $polarity= \Tweets with Positive Sentiment / \Tweets with Negative Sentiment$ was used to correlate positive sentiments with revenue increases.

In 2012 Younggue Bae,Hongchul Lee examined the positive or negative influence of popular twitterers on the sentiment of audience. They started out by selecting 13 popular users and for each of them they identifies their audience, i.e. those people "who reply to, mention, or retweet about the popular user".  [Sentiment analysis of twitter audiences] Using lexicon-based sentiment analysis they were able to divide the audience into two groups: those who are in favour and those who are against the popular user. They then proceeded on investigating the relationship between the user sentiment and his audience one. The results showed a general positive correlation between the two, meaning that positive Tweets of a popular user were followed by positive retweets and viceversa. This result constitutes an important assumption for our research: we can generalize an audience mood by investigating the polarity and sentiment of a popular user, which facilitates our data collection and analysis.
Last but not least, they investigated the relationship between real-world landscape and influence of popular users and found a strong casuality correlation. This too appears to be an important result: Twitter can be used as a predictor of real world landscape.






## Influence and Prediction 1.1

